### ISSUE TITLE
Application lacks a user interface.

### ISSUE THREAD

**Issue by absenth** [absenth/agridies#15]
This application should have a web, or terminal user interface.
Ideally this would display some useful information, such as the 5 or 10 most recent entries.
Band and Mode data.  And if a possible Dupe is detected.

some options to investigate might be:
* Cement - a modern terminal ui
* ncurses - a terminal ui that's been around forever
* flask - a web framework

**Comment by MVorkosigan** [comment]
I would like to try my luck at this. Havent done anything similar yet, though, so chances are 50/50 at best that its gonna work

**Comment by absenth** [comment]
Sounds good,

I was just starting to look at py_cui linked in the readme

**Comment by absenth** [comment]
This could be a web interface, using something like Flask.
or it could be a terminal user interface using something like ncurses, concrete, or py_cui

I think, it would be great if the final version had an input section where the "contesting()" function ran in a loop.
maybe a display section that shows the last 10 or so log entries.  And then from there I guess anything is negotiable.

**Comment by MVorkosigan** [comment]
Ok, so here a first screenshot of what my first try using ncurses looks like. In the top window, further entries can be added, the bottom window is for user input. In the finished state, the top window will obviously be much fuller
![2021-06-05_14-00](https://user-images.githubusercontent.com/71211661/120891288-07ede000-c608-11eb-8a74-5b4b2554889f.png)

**Comment by MVorkosigan** [comment]
A screenshot of how my first try using ncurses looks like.
![2021-06-05_14-43](https://user-images.githubusercontent.com/71211661/120892064-9c5a4180-c60c-11eb-9f31-1c82cd8644ad.png)

**Comment by absenth** [comment]
That looks like an awesome start!
